language: c

# Tool setup.
install:
  - sudo apt-get install -qq lua5.1
  - sudo apt-get install -qq lua5.2
  - sudo apt-get install -qq luajit
  - sudo ln -s /usr/bin/luajit-2.0.0-beta9 /usr/bin/luajit
  - sudo apt-get install -qq luarocks
  - sudo luarocks install https://raw.github.com/justincormack/ljsyscall/master/rockspec/ljsyscall-scm-1.rockspec
  - git clone git://github.com/fperrad/lua-TestMore.git
  - sudo make -C lua-TestMore install LUAVER=5.1
  - sudo make -C lua-TestMore install LUAVER=5.2

# Build and test.
script:
  - make LUA=luajit test
  - make LUA=lua5.1 test
  - make LUA=lua5.2 test

branches:
  only:
    - master

